kind: pipeline
name: checks

steps:
  - name: restore
    image: plugins/s3-cache
    settings:
      pull: true
      endpoint: https://s3.amazonaws.com
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      restore: true
      path: regnum-ci/cache
  - name: compile
    image: openjdk:12-jdk-oraclelinux7
    commands:
        - ./gradlew -Dorg.gradle.daemon=false compileJava compileKotlin
  - name: dokka
    image: openjdk:12-jdk-oraclelinux7
    commands:
      - ./gradlew -Dorg.gradle.daemon=false dokka
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request
  - name: publish
    image: plugins/gh-pages
    settings:
      username: SchlaubiBot
      password:
        from_secret: github_password
      pages_directory: public/
    when:
      branch:
        - master
      event:
        exclude:
          - pull_request
  - name: rebuild
    image: plugins/s3-cache
    settings:
      pull: true
      endpoint: https://s3.amazonaws.com
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      rebuild: true
      path: regnum-ci/cache
      mount:
        - .gradle/wrapper
        - .gradle/caches
