kind: pipeline
name: checks

steps:
  - name: compile
    image: openjdk:12-jdk-oraclelinux7
    commands:
        - ./gradlew -Dorg.gradle.daemon=false compileJava compileKotlin
  - name: dokka
    image: openjdk:12-jdk-oraclelinux7
    commands:
      - ./gradlew -Dorg.gradle.daemon=false dokka
    when:
      branch:
        - master
  - name: publish
    image: plugins/gh-pages
    settings:
      username: SchlaubiBot
      password:
        from_secret: github_password
      pages_directory: public/
      when:
        branch:
          - master